services:
  drf_app:
    command: ../scripts/tests.sh
    volumes:
      - "../androxine:/app/androxine"
    env_file:
      - path: ../.env.tests
        required: false
    environment:
      DEBUG: 1
      SECRET_KEY: "django-insecure-ef7dxcp(*tz^s23r-x!m$2f&2(d4d)*0&*@aimo3))9&@g275k"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: "androxine_db"
      DB_USER: "postgres"
      DB_PASS: 1111
      DB_HOST: "db"
      DB_PORT: 5432
      ELASTICSEARCH_HOST: "elasticsearch"
      ELASTICSEARCH_PORT: 9200
      REDIS_CACHE_URL: "redis://redis_cache:6380/0"
      LOGLEVEL: "CRITICAL"
    restart: no
    depends_on:
      elasticsearch:
        condition: service_healthy
