version: "3"

services:
  drf_app:
    build:
      context: ../
      dockerfile: app.Dockerfile
    container_name: AndroxineBackendDjango
    restart: always

  # elasticsearch:
  #   image: elasticsearch:8.14.0
  #   container_name: AndroxineBackendElasticsearch
