services:
  backend_nginx:
    build: ../nginx
    container_name: AndroxineBackendNginx
    volumes:
      - static_volume:/app/androxine/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - drf_app

  drf_app:
    command: >
      sh -c " ../scripts/django.sh &&
              ../scripts/search_index.sh &&
              gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/androxine/staticfiles
    expose:
      - 8000
    env_file:
      - ../.env.prod
    depends_on:
      db:
        condition: service_healthy
      celery_redis_broker:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      redis_cache:
        condition: service_started

  celery_worker:
    volumes:
      - static_volume:/app/androxine/staticfiles
    env_file:
      - ../.env.prod

volumes:
  static_volume:
