version: "3"

services:
  elasticsearch:
    image: elasticsearch:8.14.0
    container_name: AndroxineBackendElasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always

volumes:
  esdata:
