services:
  drf_app:
    command: >
      sh -c " python manage.py search_index --create &&
              coverage run manage.py test -v 2 && 
              coverage report &&
              coverage html"
    volumes:
      - "../androxine:/app/androxine"
    env_file:
      - ../.env.tests
    restart: on-failure
    depends_on:
      elasticsearch:
        condition: service_healthy
