services:
  drf_app:
    command: >
      sh -c " coverage run manage.py test -v 2 && 
              coverage report &&
              coverage html"
    volumes:
      - "../androxine:/app/androxine"
    env_file:
      - ../.env.tests
    restart: on-failure
