FROM node:14-alpine AS builder
ENV NODE_ENV production

WORKDIR /app

COPY ./androxine/package.json .
RUN npm i

COPY ./androxine .
COPY ./.env.prod .env

RUN npm run build

FROM nginx:stable as production
ENV NODE_ENV production

COPY --from=builder /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]