# Generated by Django 5.1 on 2024-08-13 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_user_is_active'),
        ('workout_template', '0002_alter_exerciseapproachinworkouttemplate_ordinal_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkoutSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workout_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('break_between_approaches', models.PositiveSmallIntegerField(default=120)),
            ],
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='break_between_approaches',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
