# Generated by Django 5.1 on 2024-08-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_template', '0003_userworkoutsettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWorkoutSettings',
        ),
    ]
