# Generated by Django 5.1 on 2024-08-20 10:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_template', '0004_delete_userworkoutsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseapproachinworkouttemplate',
            name='relative_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
