# Generated by Django 5.1 on 2024-08-22 14:53

import config.utils
import config.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_template', '0005_alter_exerciseapproachinworkouttemplate_relative_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseapproachinworkouttemplate',
            name='exercise_in_workout_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='workout_template.exerciseinworkouttemplate', validators=[
                                    config.validators.RestrictAmountValidator('workout_template', 'ExerciseApproachInWorkoutTemplate', 'exercise_in_workout_template', 30)]),
        ),
        migrations.AlterField(
            model_name='exerciseinworkouttemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_template.workouttemplate', validators=[
                                    config.validators.RestrictAmountValidator('workout_template', 'ExerciseInWorkoutTemplate', 'template', 20)]),
        ),
    ]
