# Generated by Django 5.1 on 2024-08-18 05:09

import config.utils
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.UUIDField(default=config.utils.current_timestamp_ulid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('body_weight', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='Weight records should be unique for each user per day')],
            },
        ),
    ]
