# Generated by Django 5.1.1 on 2024-09-29 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_user_is_active'),
        ('weight', '0002_weight_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkoutSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='weight_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('started_weight', models.FloatField()),
                ('desired_weight', models.FloatField()),
            ],
        ),
    ]
