# Generated by Django 5.0.7 on 2024-08-01 13:17

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_exercise_slug_alter_exercisecategory_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisecategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='name', unique=True),
        ),
        migrations.CreateModel(
            name='UserExerciseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_time_maximum', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userexercisesettings',
            constraint=models.UniqueConstraint(fields=('user', 'exercise'), name='unique exercise for every user'),
        ),
    ]
