# Generated by Django 5.0.6 on 2024-08-21 03:40

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_remove_exercisecategory_slug_alter_exercise_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercisesettings',
            name='temp_id',
            field=models.UUIDField(default=config.utils.current_timestamp_ulid, editable=False, unique=True),
        ),
    ]
