# Generated by Django 5.0.6 on 2024-08-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_remove_userexercisesettings_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexercisesettings',
            old_name='temp_id',
            new_name='id',
        ),
    ]
