# Generated by Django 5.1 on 2024-08-22 10:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_alter_exercise_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, max_length=255, populate_from='name', unique=True),
        ),
    ]
