# Generated by Django 5.1 on 2024-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_exercisecategory_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='Exercise names must be unique for every category'),
        ),
    ]
