services:
  react_app:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    volumes:
      - ../androxine/src:/app/src
      - ../androxine/public/locales:/app/public/locales
    ports:
      - "3000:3000"
    env_file:
      - ../.env.dev
