# Generated by Django 5.1 on 2024-08-19 10:23

import config.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0003_remove_exercisecategory_slug_alter_exercise_slug_and_more'),
        ('workout_template', '0004_delete_userworkoutsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseInWorkout',
            fields=[
                ('id', models.UUIDField(default=config.utils.current_timestamp_ulid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseApproachInWorkout',
            fields=[
                ('id', models.UUIDField(default=config.utils.current_timestamp_ulid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('reps', models.PositiveIntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('exercise_in_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='workout.exerciseinworkout')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=config.utils.current_timestamp_ulid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('beginning_datetime', models.DateTimeField(auto_now_add=True)),
                ('enging_datetime', models.DateTimeField(blank=True, null=True)),
                ('break_between_approaches', models.PositiveSmallIntegerField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_template.workouttemplate')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseinworkout',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.workout'),
        ),
    ]
