# Generated by Django 5.1 on 2024-08-22 14:53

import config.utils
import config.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseapproachinworkout',
            name='exercise_in_workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approaches', to='workout.exerciseinworkout', validators=[
                                    config.validators.RestrictAmountValidator('workout', 'ExerciseApproachInWorkout', 'exercise_in_workout', 30)]),
        ),
        migrations.AlterField(
            model_name='exerciseinworkout',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.workout', validators=[
                                    config.validators.RestrictAmountValidator('workout', 'ExerciseInWorkout', 'workout', 20)]),
        ),
    ]
