name: backend tests
on:
  push:
    paths:
    - 'backend/**'
  pull_request:
    paths: 
    - 'backend/**'

jobs:
  linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install deps
        run: pip install -r ./requirements.txt

      - name: run linter
        run: flake8 .

  tests:
    needs: linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./backend.compose.test.yaml"
          cwd: "./backend"
          up-flags: "--exit-code-from=drf_app --abort-on-container-exit"
