name: backend tests
on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install deps
        run: pip install -r ./requirements.txt

      - name: run linter
        run: flake8 .

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install deps
        run: pip install -r ./requirements.txt

      - name: run tests
        working-directory: ./androxine
        run: python manage.py test
